name: Bump

on:
  schedule:
    # Run every hour.
    - cron: "0 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  bump:
    runs-on: macos-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v6
      - name: Set up Git
        run: |
          git config --global user.name 'HongBot'
          git config --global user.email '109153616+hong-bot@users.noreply.github.com'
      - uses: Homebrew/actions/setup-homebrew@main
      - name: Bump packages
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }} # A PAT for hong-bot which will trigger workflows run.
        run: |
          brew bump --no-fork --open-pr --casks --tap=$GITHUB_REPOSITORY
